# Generated by Django 5.0.6 on 2024-07-27 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0003_sessionupload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SessionUpload",
        ),
    ]
