# Generated by Django 5.0.6 on 2024-07-27 00:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0004_delete_sessionupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
